# Generated by Django 4.2.2 on 2023-06-20 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chiqim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.FloatField()),
                ('izoh', models.CharField(max_length=500)),
                ('masul', models.CharField(blank=True, max_length=200, null=True)),
                ('sana', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('narx1', models.FloatField()),
                ('narx2', models.FloatField(blank=True, null=True)),
                ('miqdor', models.IntegerField()),
                ('izoh', models.TextField(blank=True, null=True)),
                ('sana', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot_turi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avtomobil', models.CharField(blank=True, max_length=150, null=True)),
                ('avto_raqam', models.CharField(blank=True, max_length=20, null=True)),
                ('summa', models.FloatField()),
                ('sana', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Savdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.IntegerField()),
                ('summa', models.FloatField()),
                ('mahsulot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.mahsulot')),
                ('mijoz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savdolar', to='mainApp.mijoz')),
            ],
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='turi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.mahsulot_turi'),
        ),
    ]
