# Generated by Django 4.2.2 on 2023-06-20 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mijoz',
            name='sana',
        ),
        migrations.RemoveField(
            model_name='mijoz',
            name='summa',
        ),
    ]
