# Generated by Django 4.2.2 on 2023-06-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_remove_mijoz_sana_remove_mijoz_summa'),
    ]

    operations = [
        migrations.AddField(
            model_name='savdo',
            name='sana',
            field=models.DateField(default='2023-01-01'),
            preserve_default=False,
        ),
    ]
